CREATE TABLE "notes" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "content" text,
  "date_created" TIMESTAMPTZ DEFAULT now(),
  "folder_id" INT REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);